name: Release
on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # to publish via OIDC
      contents: read # to checkout repo
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      # Ensure npm 11.5.1 or later is installed, to support OIDC publishing
      - name: Update npm
        run: npm install -g npm@latest

      - name: Bump version
        run: jq ".version = \"$version\"" package.json > tmp && mv tmp package.json
        env:
          version: ${{ github.event.release.tag_name }}

      - name: Install dependencies
        run: npm clean-install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Publish
        run: npm publish ./dist --access public
