name: Release
on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout repo
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      - name: Bump version
        run: jq ".version = \"$version\"" package.json > tmp && mv tmp package.json
        env:
          version: ${{ github.event.release.tag_name }}

      - name: Install dependencies
        run: npm clean-install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Publish
        run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
