name: Security Veracode policy scan
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"
jobs:
  security-veracode-policy-check:
    name: Security Veracode policy scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_policy_scan.yml@v2
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
